### ISSUE TITLE
Language in en.csv

### ISSUE THREAD

**Issue by MichielDePaepe** [henningms/nibe-s1255-modbus#1]
The registry titles are mostly in Norwegian in en.csv, they used to be in English

**Comment by henningms** [comment]
Oops, I must have renamed the file wrong. Thanks for pointing that out! Will update shortly

**Comment by henningms** [comment]
Fixed. Also updated the FW on my heat pump to 3.0.10 and exported again so the modbus registers should be up to date.

Have a great day!
